#!/usr/bin/env bash

action=$1
flag=$2
shift

[ "$action" = "usage" ] && {
  echo "  Visualize tasks by due date:"
  echo "    due"
  echo "      default behaviour generates a list tasks due today or overdue"
  echo "      Optional argument (integer n) also shows tasks due in next n days."
  echo ""
  exit
}

[ "$action" = "due" ] && {
     python3 $(dirname $0)/due.py "$TODO_FILE" $flag
}
